#!/usr/bin/env bash

Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'

commit_regex='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\(HYT+-[0-9]+\): [A-Za-z0-9]+'
commit_to_check=$(head -1 $1)

echo
echo -e ${Yellow}"Checking if the commit is within the standard..."
echo

if [[ "${commit_to_check}" =~ ${commit_regex} ]]; then
    echo -e ${Green}"[PASSED]:" ${commit_to_check}
else
    echo -e ${Red}"[REJECTED]:" ${commit_to_check}
    exit 1
fi
exit 0